name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin # Swap to graalvm if we end up using AOT or other graal specific features
          java-version: "25"
      - run: ./mvnw -B -ntp spotless:check
